---
elasticsearchHosts: "http://es.bigdata-dev.ml"

replicas: 1

image: "docker.elastic.co/kibana/kibana-oss"
imageTag: "7.9.1"
imagePullPolicy: "IfNotPresent"

# additionals labels
labels:
  app.kubernetes.io/name: "elasticsearch"
  app.kubernetes.io/component: "kibana"
  app.kubernetes.io/version: "7.9.1"
  app.kubernetes.io/managed-by: "helm"

resources:
  requests:
    cpu: "1000m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

httpPort: 5601


service:
  type: ClusterIP
  loadBalancerIP: ""
  port: 5601
  nodePort: ""
  labels: {}
  annotations: {}
    # cloud.google.com/load-balancer-type: "Internal"
    # service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
    # service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"
  loadBalancerSourceRanges: []
    # 0.0.0.0/0

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - kibana.bigdata-dev.ml
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
