apiVersion: v1
kind: Service
metadata:
  name: {{ include "debezium-kafka-connect.fullname" . }}
  labels:
    {{- include "debezium-kafka-connect.labels" . | nindent 4 }}
spec:
  {{- with .Values.service }}
  type: {{ .type }}
  ports:
    - port: {{ .restService.port }}
      protocol: TCP
      name: {{ .restService.name | quote }}
    - port: {{ .jmxService.port }}
      protocol: TCP
      name: {{ .jmxService.name | quote }}
  {{- end }}
  selector:
    {{- include "debezium-kafka-connect.selectorLabels" . | nindent 4 }}