kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "innotech-frontend.fullname" . }}-env
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
{{ include "innotech-frontend.labels" . | indent 4 }}
data:
  env-config.js: |-
    window._env_ = {
        CONFIG_URL: "https://PUBLIC_DOMAIN/config/{{ .Values.vendorId }}/web-K8S_NAMESPACE.json"
    }
