kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "innotech-frontend.fullname" . | printf "%s-env" | quote }}
  namespace: {{ .Values.project.namespace | quote }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
{{ include "innotech-frontend.labels" . | indent 4 }}
data:
  env-config.js: |-
    window._env_ = {
        CONFIG_URL: "https://{{ .Values.project.publicDomain }}/config/{{ .Values.project.vendorId }}/web-{{ .Values.project.namespace }}.json"
    }
