apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "innotech-frontend.fullname" . }}
  labels:
{{ include "innotech-frontend.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600s"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "3600s"
spec:
  # tls:
  # - hosts:
  #   - INGRESS_HOST.DOMAIN_NAME
  rules:
  - host: {{ include "innotech-frontend.ingressHost" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "innotech-frontend.fullname" . }}
          servicePort: {{ .Values.service.port }}
