apiVersion: v1
kind: Service
metadata:
  name: {{ include "innotech-frontend.fullname" . }}
  labels:
{{ include "innotech-frontend.labels" . | indent 4 }}
spec:
  ports:
  - name: http-{{ .Values.service.port }}
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    # nodePort: CONTAINER_PORT
  selector:
    app: {{ .Release.Name | quote }}
    version: {{ .Values.image.tag | quote }}
    venderid: {{ .Values.vendorId | quote }}
    platformid: {{ .Values.platformId | quote }}
