apiVersion: v1
kind: Service
metadata:
  name: {{ include "innotech-frontend.fullname" . | quote }}
  namespace: {{ .Values.project.namespace | quote }}
  labels:
{{ include "innotech-frontend.labels" . | indent 4 }}
spec:
  ports:
  - name: http-{{ .Values.service.port }}
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "innotech-frontend.appName" . | quote }}
    version: {{ .Values.image.tag | quote }}
    venderid: {{ .Values.project.vendorId | quote }}
    platformid: {{ .Values.project.platformId | quote }}
